### PR TITLE
Update action.yml

### PR DESCRIPTION
**Pull request by Reza-SadriNia**

### CODE REVIEW

**Review by Xanax-C-137 — APPROVED** [review]

**Comment by Reza-SadriNia** [comment]
Added changes from Original PR

**Review by PabloCastellano — APPROVED** [review]

**Comment by PabloCastellano** [comment]
Any chance to get it merged?

**Review by PabloCastellano — CHANGES_REQUESTED** [review]
I'm not experienced with github actions but I think you need to update the parameters in entrypoint.sh now ($2, $3, $4...)

**Comment by wlixcc** [comment]
Only parameters are added, no logic is specified

**Pull request closed without merging**
